### PR TITLE
Provide callbacks for 'publish' and 'respond' events

### PR DESCRIPTION
**Pull request by emilsoman**
This will allow other transport mechanisms to be used apart from zmq and also a way to extract messages to files etc.

### CODE REVIEW

**Comment by iffyuva** [comment]
can you give me some background for this PR?
and how can i test it?

**Comment by emilsoman** [comment]
Rbkit by default works with only zmq REQ-REP and PUB-SUB sockets. This means we have to depend on 2 open ports if we were to get any data into or out of Rbkit. This will be okay in dev environments. But when we're talking about apps running in the cloud , heroku, for example may not have these ports available.

This change in rbkit will allow users to extract data out of rbkit server and handle the data however they wish. This means you can write an rbkit extension gem which taps this data from the server and sends it over websockets , or simply dump it into a file. See [this doc](https://github.com/code-mancers/rbkit/blob/io-callbacks/docs/extension.md) to see how you can test it.

**Comment by emilsoman** [comment]
@iffyuva It's not a critical feature , but can this PR be merged if you think it doesn't have any side effects ?

**Comment by iffyuva** [comment]
@emilsoman yes, this can be merged. i don't see any issues. one concern that i have is: can we zeromq as client for publish/respond events?

**Pull request merged**
