### PR TITLE
Capture object age along with heap snapshot

### PR DESCRIPTION
**Pull request by emilsoman**

### CODE REVIEW

**Comment by emilsoman** [comment]
Don't merge, re-implementing with `rb_gc_count`

**Comment by gnufied** [comment]
So, I found value of `get_obj_age` vary wildly between ruby versions and OS versions. On ruby 2.2 on both OSX and Linux, for an object which has not seen any GC - the returned value is `0`. But on Ruby 2.1.x the value for a new object is `1`.

The problem is on Ruby 2.2.0 for an object which has seen GC the returned value from `get_obj_age` is `1`, so we can't really tell which generation object belongs to.

**Comment by gnufied** [comment]
Further thought, I don't think using https://github.com/ruby/ruby/blob/123eeb1c1a904923754ce65148dbef045b56e083/gc.c#L926-L930 will work on Ruby 2.1.x because Ruby 2.1.x does not uses same way of tracking object generation as Ruby 2.2.x

**Comment by emilsoman** [comment]
Yeah, I too just figured we can't use this for consistent results. Let's go
with using rb_gc_count() , but only those objects which gave object
creation trace would have a non-nil value for "age" field.

**Pull request closed without merging**
